name: Report Issues
on: issues
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Give the status
        uses: actions/checkout@v3
      - name: Report issue
        run: echo "${{toJSON(github)}}"
